### ISSUE TITLE
How could change the Page size from "letter" to "A4"

### ISSUE THREAD

**Issue by kiritjp** [ronaldotn/paper-view#5]
Can you please guide to change the page size from "letter" to "A4"

**Comment by ronaldotn** [comment]
In file /examples/assets/styles/paper.css replacer
@page {
  size: letter;
  margin: 25mm 25mm;
  .
  .
  .
}

replace size to A4
and replace /node_modules/paper-view/dist/css/paper.css by custom file css with size A4
